#! python


'''
DIFFERENT DATASET SPECIFICATIONS FOR REGRESSION ON INDICATOR VARIABLES:
    'EST'  = OLS estimates from regressing main variables (mortality, expropr. risk, GDP) on
             campaign and laborer indicators
    'CORR' = Correlation of expropriation risk and GDP with mortality (with and without indicators)

DIFFERENT DATASET SPECIFICATIONS FOR FIRST STAGE AND IV ESTIMATION:
    1 = PANEL_A: Original mortality data (64 countries)
    2 = PANEL_B: Only countries with non-conjectured mortality rates (rest: 28 countries)
    3 = PANEL_C: Original data (64 countries) with campaign and laborer indicators
    4 = PANEL_D: Only countries with non-conjectured mortality rates, campaign + laborer indicators
    5 = PANEL_E: As Panel D with new data provided by AJR
'''

# Illustrate simple use of run_do_script for the data that underlies table
# 1.


def build(ctx):

    ctx(
        features='run_do_script',
        source='regression.do',
        target=[
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'log', 'regression.log'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'regression.dta'),
            ctx.path_to(ctx, 'OUT_ANALYSIS',
                        'fhpolrigaug_estimation_results.dta'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'polity4_estimation_results.dta')
        ],
        deps=[
            ctx.path_to(ctx, 'OUT_DATA', '5_year_panel_all.dta'),
            ctx.path_to(ctx, 'OUT_DATA', 'annual_panel_all.dta'),
            ctx.path_to(ctx, 'OUT_DATA', '10_year_panel_all.dta'),
            ctx.path_to(ctx, 'OUT_DATA', '20_year_panel_all.dta'),
            ctx.path_to(ctx, 'OUT_MODEL_SPECS', 'FHI.do')
        ]
    )
