#! python


def build(ctx):

    ctx(
        features='tex',
        source='research_paper.tex',
        prompt=1,
    )
    ctx.install_files(
        ctx.env.PROJECT_PATHS['PROJECT_ROOT'].abspath(),
        'research_paper.pdf'
    )
