#! python


def build(ctx):

    figures = [
        'F1',
        'F2',
        'F3',
        'F4',
        'F5',
        'F6'
    ]

    for f in figures:

        if f == 'F6':
            ctx(
                features='subst',
                source='figures6.do',
                target='{}_figures6.do'.format(f)
            )
            ctx(
                features='run_do_script',
                source='{}_figures6.do'.format(f),
                target=[
                    ctx.path_to(ctx, 'OUT_FINAL', 'log',
                                '{}_figures6.log'.format(f)),
                    ctx.path_to(ctx, 'OUT_FIGURES',
                                '{}.eps'.format(f))
                ],
                deps=[
                    ctx.path_to(ctx, 'OUT_DATA', '{}_all.dta'.format(f))
                ],
                name='{}_figures6'.format(f),
                append=f
            )

        else:
            ctx(
                features='subst',
                source='figures.do',
                target='{}_figures.do'.format(f)
            )
            ctx(
                features='run_do_script',
                source='{}_figures.do'.format(f),
                target=[
                    ctx.path_to(ctx, 'OUT_FINAL', 'log',
                                '{}_figures.log'.format(f)),
                    ctx.path_to(ctx, 'OUT_FIGURES',
                                '{}.eps'.format(f))
                ],
                deps=[
                    ctx.path_to(ctx, 'OUT_DATA', '{}_all.dta'.format(f))
                ],
                name='{}_figures'.format(f),
                append=f
            )
