#! python


def build(ctx):

    tables = [
        'FHI',
        'POL'
    ]

    figures = [
        'F1',
        'F2',
        'F3',
        'F4',
        'F5',
        'F6'
    ]

    for t in tables:

        ctx(
            features='subst',
            source='table12.do',
            target='{}_table12.do'.format(t)
        )
        ctx(
            features='run_do_script',
            source='{}_table12.do'.format(t),
            target=[
                ctx.path_to(ctx, 'OUT_FINAL', 'log',
                            '{}_table12.log'.format(t)),
                ctx.path_to(ctx, 'OUT_TABLES',
                            '{}.tex'.format(t))
            ],
            deps=[
                ctx.path_to(ctx, 'OUT_ANALYSIS',
                            '{}_estimation_results.dta'.format(t))
            ],
            name='{}_table12'.format(t),
            append=t
        )

        ctx(
            features='subst',
            source='robust_table.do',
            target='{}_robust_table.do'.format(t)
        )
        ctx(
            features='run_do_script',
            source='{}_robust_table.do'.format(t),
            target=[
                ctx.path_to(ctx, 'OUT_FINAL', 'log',
                            '{}_robust_table.log'.format(t)),
                ctx.path_to(ctx, 'OUT_TABLES',
                            '{}_robust.tex'.format(t))
            ],
            deps=[
                ctx.path_to(ctx, 'OUT_ANALYSIS',
                            '{}_robustness_check_results.dta'.format(t))
            ],
            name='{}_robust_table'.format(t),
            append=t
        )

        ctx(
            features='subst',
            source='IV_table.do',
            target='{}_IV_table.do'.format(t)
        )
        ctx(
            features='run_do_script',
            source='{}_IV_table.do'.format(t),
            target=[
                ctx.path_to(ctx, 'OUT_FINAL', 'log',
                            '{}_IV_table.log'.format(t)),
                ctx.path_to(ctx, 'OUT_TABLES',
                            '{}_nsave_IVtable.tex'.format(t)),
                ctx.path_to(ctx, 'OUT_TABLES',
                            '{}_worldincome_IVtable.tex'.format(t))

            ],
            deps=[
                ctx.path_to(ctx, 'OUT_ANALYSIS',
                            '{}_nsaveup_IVestimation_results.dta'.format(t)),
                ctx.path_to(ctx, 'OUT_ANALYSIS',
                            '{}_worldincomeup_IVestimation_results.dta'.format(t)),
                ctx.path_to(ctx, 'OUT_ANALYSIS',
                            '{}_nsavedo_IVestimation_results.dta'.format(t)),
                ctx.path_to(ctx, 'OUT_ANALYSIS',
                            '{}_worldincomedo_IVestimation_results.dta'.format(t))

            ],
            name='{}_IV_table'.format(t),
            append=t
        )

    for f in figures:


        ctx(
            features='subst',
            source='figures.do',
            target='{}_figures.do'.format(f)
        )
        ctx(
            features='run_do_script',
            source='{}_figures.do'.format(f),
            target=[
                ctx.path_to(ctx, 'OUT_FINAL', 'log',
                            '{}_figures.log'.format(f)),
                ctx.path_to(ctx, 'OUT_FIGURES',
                            '{}.png'.format(f))
            ],
            deps=[
                ctx.path_to(ctx, 'OUT_DATA', '{}_all.dta'.format(f))
            ],
            name='{}_figures'.format(f),
            append=f
        )

    ctx(
        features='run_do_script',
        source='long_table.do',
        target=[
            ctx.path_to(ctx, 'OUT_FINAL', 'log',
                        'long_table.log'),
            ctx.path_to(ctx, 'OUT_TABLES',
                        'long_run_table.tex')
        ],
        deps=[
            ctx.path_to(ctx, 'OUT_ANALYSIS',
                        'long_run_25.dta'),
            ctx.path_to(ctx, 'OUT_ANALYSIS',
                        'long_run_50.dta')
        ],
        name='long_table',
    )
    ctx(
        features='run_do_script',
        source='very_long_table.do',
        target=[
            ctx.path_to(ctx, 'OUT_FINAL', 'log',
                        'very_long_table.log'),
            ctx.path_to(ctx, 'OUT_TABLES',
                        'very_long_A.tex'),
            ctx.path_to(ctx, 'OUT_TABLES',
                        'very_long_B.tex')
        ],
        deps=[
            ctx.path_to(ctx, 'OUT_ANALYSIS',
                        'very_long_A.dta'),
            ctx.path_to(ctx, 'OUT_ANALYSIS',
                        'very_long_B.dta')
        ],
        name='very_long_table',
    )
